# Model configurations for StoDir

model_params:
  n_estimators: 200
  min_samples_split: 50
  random_state: 42

features:
  # NOTE: Justification for choosing the following horizons
  # 2 days: Short term view
  # 5 days Weekly view
  # 60 days: 2 months for business cycle
  # 250 days: Yearly view
  # 1000 days Long term view
  start_date: "2010-01-01"
  horizons: [2, 5, 60, 250, 1000]

data:
  portfolios:
    - sp500
    - nasdaq100
    - nifty50
    - ftse100
    - dax

backtesting:
  # The minimum number of trading days to use for the first training period.
  # 250 days is roughly one year. 1000 is ~4 years.
  start: 1000

  # The number of trading days to predict forward in each backtest step.
  step: 250