# Model configurations for StoDir 

model_params:
  n_estimators: 200
  min_samples_split: 50
  random_state: 42

features:
  horizons: [2, 5, 60, 250, 1000]

data:
  training_tickers: ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "TSLA"]

